apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tuto-sops-secret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:zmCTBbmIOAQYxPaiX7w=,iv:fbBmfhOAQgt5usJlQgzjKwdkjY9QviyVQ/8Hse17BQw=,tag:Beq0YHTktafK3AV81JGuOQ==,type:str]
          stringData:
            PG_PASSWORD: ENC[AES256_GCM,data:DD/JqsvJ8XmjiJhmvgIs,iv:eOT1zZ3H9YaV/rqtZf/MmF5qHiJWc1Uy++HV5X8EpUw=,tag:5ZTtfeHiV4gHCuwHuCTUNw==,type:str]
            PG_ROOT_PASSWORD: ENC[AES256_GCM,data:c/etn1be2w8XujVP2x2W,iv:C+8UggObGJ1Pb4fYFa+eg3dwQxX9cGwRBARQggkInk8=,tag:xhVe/8ZAr/z7EJhCLydY7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qt7e329qjlhqsfsyxsvws56ukp2f9h0ktmj45atleqk0q406mfhstwnudv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUHhYQkR1Y0xVbm1uemRY
            eE1nNXBJWm4rS3p4MVBKbFFmU25wRkdIMXlVCm5Ec2xaNlByZ0JsdzllRUEzc0Nw
            S1Q2Z084SEIwQVMvYjBEYzlrSlo4NmcKLS0tIHVBSmE3ZkxRejFTVnpqaHlWMXZL
            b3RzS2UzWVdlNmZ4L1lkQk5yZnlkbjQKfCTfH7tpXXO++w83nld8rt93Zfv1GwgO
            OTTKAXLLucY6dM4VYxqqoXkxKeUY5s13GlRrtyW+URxGqvNw9AejNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T14:00:22Z"
    mac: ENC[AES256_GCM,data:6XCOkNqSExrqrMtbWwihmd8cFWCJ5rfzbJtNEl3b6Yv/yaB7Iz/8YQlH/w++owMd7HB+0OdqWT77BXQOTQ9/4Y4aQNeoljU+jLjVnxDr17NPDY/aFpM+PCDvBplteiioGmuhGzn2vHwP6wGIwNDhN3TBo07vpF+UPW2sDmLIr4k=,iv:zJ+U8kM8CqIm/QS04BLlSxIjFCsycfCm1WwuRytzgZw=,tag:qjJ0ZYnJ4pTEVY9qAhXtJQ==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.8.1
